### ISSUE TITLE
Continuing issues with the Registration Window

### ISSUE THREAD

**Issue by waisanen** [jamfprofessionalservices/DEPNotify#14]
I'm still having issues with the Registration window appearing (incorrectly) a second time at the end of the DEPNotify workflow, preventing the app from quitting properly.

I'm using 1.2.0 of the depNotify script along with the updated version (1.1.2) of DEPNotify that was posted a few weeks ago in the MacAdmins Slack instance.

I thought perhaps some of the minor modifications I made to depNotify.sh might have been responsible but even copying the script exactly with zero mods still results in the Registration window coming up twice.

Here's the script parameters I'm using in my policy:
![image](https://user-images.githubusercontent.com/18560201/49048683-7d9fa800-f190-11e8-94d6-989ed7732259.png)

The test client is a freshly restored 2018 MacBook Pro running 10.14.1, managed by Jamf Pro 10.8.0.  I'm currently baffled what might be triggering this bug for me but not other people.

**Comment by kbareis** [comment]
Hey @waisanen! Please try setting `COMPLETE_METHOD_DROPDOWN_ALERT` to `false`. I think you have it called `Comp Method or Main Screen`. The fix that was put into 1.1.2 of DEPNotify fixed the main window buttons but not the drop downs. I have been working with @fgd in Slack on a fix. So that ether option can be used.

**Comment by waisanen** [comment]
Yep, that did the trick!  Thanks!
